export const extraCopy = {
  th: {
    formatLabel: 'รูปแบบแบบทดสอบ',
    profileLabel: 'โปรไฟล์',
    scopeLabel: 'ขอบเขต',
    lengthLabel: 'จำนวนข้อ',
    allCoreLabel: 'ทุกภาษา Core',
    allGameLabel: 'ทุกภาษา Game',
    identifyFormatSummary: '15/30 ข้อ / ง่าย-ยาก',
    standardSummary: 'Core + Game: ง่าย-ยาก',
    debugSummary: 'Core + Game: ง่าย-ยาก',
    fixedCoreNote: 'โหมดแก้ Error เล่นได้ทั้ง core และ game track',
    debugCoreNote: 'โหมด Debug เล่นได้ทั้ง core และ game track',
    fixErrorRules: [
      'Fix Error มีทั้ง easy และ hard ครบทั้ง core และ game-dev track',
      'โหมดนี้ยังเป็น 15 ข้อ เวลา 35 วินาทีต่อข้อ โดย easy มี hint 3 ครั้ง และ hard มี hint 5 ครั้งต่อรอบ',
      'เลือกได้ว่าจะเล่น Core หรือ Game แล้วค่อยสุ่มจากทั้งหมดหรือเจาะภาษาเดียว',
      'คำถามจะให้ดูตัวอย่างโค้ดก่อน แล้ววาง error ไว้ด้านล่างเพื่อระบุบรรทัดที่น่าจะเป็นต้นเหตุหลัก',
    ],
    debugRules: [
      'Debug มีทั้ง easy และ hard ครบทั้ง core และ game-dev track',
      'โหมดนี้ยังใช้สถานการณ์จำลอง + ข้อมูล log มี 15 ข้อ เวลา 50 วินาทีต่อข้อ โดย easy มี hint 3 ครั้ง และ hard มี hint 5 ครั้ง',
      'เลือกได้ว่าจะเล่น Core หรือ Game แล้วค่อยสุ่มจากทั้งหมดหรือเจาะภาษาเดียว',
      'โจทย์จะให้สถานการณ์, ข้อมูล log และตัวอย่างโค้ดเพื่อชี้สาเหตุหลักให้ถูกจุด',
    ],
    lengthShortLabel: '15 ข้อ',
    lengthShortDescription: 'โหมดสั้นสำหรับการฝึกแบบเร็ว',
    lengthStandardLabel: '30 ข้อ',
    lengthStandardDescription: 'โหมดมาตรฐาน 30 ข้อเต็ม',
    tryFixError: 'ลองแก้ Error',
    tryDebug: 'ลองดู Bug',
    fixErrorQuestionLabel: 'โจทย์',
    fixErrorQuestionHint: 'อ่าน flow ของ snippet นี้ก่อน แล้วค่อยใช้ error ด้านล่างเพื่อชี้ว่าบรรทัดไหนคือต้นเหตุหลัก',
    debugQuestionLabel: 'กรณี Debug',
    debugQuestionHint: 'อ่าน scenario และ log ก่อน แล้วค่อยดู snippet เพื่อชี้สาเหตุหลัก',
    debugScenarioLabel: 'สถานการณ์',
    debugLogLabel: 'ข้อมูล log',
    debugGuideTitle: 'คู่มือ Debug',
    fixErrorGuideTitle: 'คู่มือแก้ Error',
    errorTextLabel: 'ข้อความ Error',
    culpritLabel: 'จุดที่น่าจะพัง',
    correctLineLabel: 'บรรทัดต้นเหตุ',
    debugRootCauseLabel: 'สาเหตุหลัก',
    debugCorrectCauseLabel: 'สาเหตุหลัก',
    choiceWhyLabel: 'เหตุผลของแต่ละบรรทัด',
    allCoreDescription: 'สุ่มข้ามภาษา core ที่รองรับทั้งหมด',
    allGameDescription: 'สุ่มข้าม game stack ที่รองรับทั้งหมด',
    singleCoreDescription: 'เจาะภาษาเดียวเพื่อซ้อมแก้จุดพัง',
    scopeNote: 'เฟสแรกยังไม่รวม html, css, json และ flutter',
    debugScopeNote: 'เฟสแรกยังไม่รวม html, css, json และ flutter',
    fixErrorBadge: 'Core + Game',
    debugBadge: 'Core + Game',
    fixErrorResultNote: 'สรุปโหมดแก้ Error จะวัดหัวข้ออ่อนตามภาษา ไม่ใช่ตามตัวเลือกบรรทัด',
    debugResultNote: 'สรุปโหมด Debug จะวัดจุดพลาดตามภาษาและสาเหตุหลัก',
    vocabSummary: '15/30 ข้อ / ง่าย-ยาก / 3-7 คำใบ้',
    vocabCoreNote: 'โหมดฝึกศัพท์เล่นได้ทั้ง core และ game track',
    vocabRules: [
      'โหมดฝึกศัพท์มีทั้ง easy และ hard พร้อมตัวเลือก 15 หรือ 30 ข้อ',
      'ใช้เวลา 25 วินาทีต่อข้อ โดยรอบ 15 ข้อจะมี hint 3/5 และรอบ 30 ข้อจะมี hint 5/7 สำหรับ easy/hard ตามลำดับ',
      'เลือกได้ว่าจะเล่น Core หรือ Game แล้วค่อยสุ่มจากทั้งหมดหรือเจาะภาษาเดียว',
      'แต่ละข้อจะแสดง keyword/syntax พร้อม snippet ตัวอย่าง ให้เลือกความหมายที่ถูกต้อง และรอบ 30 ข้อจะไม่ซ้ำแม้เลือกภาษาเดียว',
    ],
    tryVocab: 'ลองฝึกศัพท์',
    vocabQuestionLabel: 'คำศัพท์',
    vocabQuestionHint: 'อ่าน snippet ตัวอย่างการใช้งานก่อน แล้วค่อยเลือกความหมายที่ตรงที่สุด',
    vocabGuideTitle: 'คู่มือฝึกศัพท์',
    vocabTermLabel: 'คำศัพท์',
    vocabMeaningLabel: 'ความหมาย',
    vocabCorrectMeaningLabel: 'ความหมายที่ถูกต้อง',
    vocabResultNote: 'สรุปโหมดฝึกศัพท์จะวัดจุดอ่อนตามภาษาและคำศัพท์',
    vocabBadge: 'Core + Game · 15/30',
  },
  en: {
    formatLabel: 'Quiz Format',
    profileLabel: 'Profile',
    scopeLabel: 'Scope',
    lengthLabel: 'Round length',
    allCoreLabel: 'All Core',
    allGameLabel: 'All Game',
    identifyFormatSummary: '15/30 questions / Easy-Hard',
    standardSummary: 'Core + Game: Easy-Hard',
    debugSummary: 'Core + Game: Easy-Hard',
    fixedCoreNote: 'Fix Error is available on both core and game tracks',
    debugCoreNote: 'Debug is available on both core and game tracks',
    fixErrorRules: [
      'Fix Error now has full easy and hard profiles on both the core and game-dev tracks.',
      'Rounds still use 15 questions and 35 seconds per question, with 3 shared hints on easy and 5 on hard.',
      'Choose Core or Game, then shuffle across All or drill into a single language.',
      'Each question shows the snippet first, then places the error underneath before you choose the culprit line.',
    ],
    debugRules: [
      'Debug now has full easy and hard profiles on both the core and game-dev tracks.',
      'Rounds still use 15 questions and 50 seconds per question, with 3 shared hints on easy and 5 on hard.',
      'Choose Core or Game, then shuffle across All or drill into a single language.',
      'Each question provides scenario, log, and snippet to identify the root cause.',
    ],
    lengthShortLabel: '15 questions',
    lengthShortDescription: 'Shorter round for quick drills.',
    lengthStandardLabel: '30 questions',
    lengthStandardDescription: 'Standard full 30-question round.',
    tryFixError: 'Try Fix Error',
    tryDebug: 'Try Debug',
    fixErrorQuestionLabel: 'Question',
    fixErrorQuestionHint: 'Read this snippet as the failing scenario first, then use the error underneath to pinpoint the culprit line.',
    debugQuestionLabel: 'Debug Case',
    debugQuestionHint: 'Read the scenario and log first, then scan the snippet to pinpoint the root cause.',
    debugScenarioLabel: 'Scenario',
    debugLogLabel: 'Runtime log',
    debugGuideTitle: 'Debug Guide',
    fixErrorGuideTitle: 'Fix Error Guide',
    errorTextLabel: 'Error',
    culpritLabel: 'Possible culprit',
    correctLineLabel: 'Culprit line',
    debugRootCauseLabel: 'Root cause',
    debugCorrectCauseLabel: 'Root cause',
    choiceWhyLabel: 'Why each line is or is not the culprit',
    allCoreDescription: 'Shuffle across every supported core language',
    allGameDescription: 'Shuffle across every supported game stack',
    singleCoreDescription: 'Drill one language at a time',
    scopeNote: 'Phase 1 excludes html, css, json, and flutter.',
    debugScopeNote: 'Phase 1 excludes html, css, json, and flutter.',
    fixErrorBadge: 'Core + Game',
    debugBadge: 'Core + Game',
    fixErrorResultNote: 'Fix Error summary tracks weak spots by language, not by line choice.',
    debugResultNote: 'Debug summary tracks weak spots by language and root cause.',
    vocabSummary: '15/30 questions / Easy-Hard / 3-7 hints',
    vocabCoreNote: 'Vocab Drill is available on both core and game tracks',
    vocabRules: [
      'Vocab Drill supports both easy and hard profiles, with 15-question and 30-question rounds.',
      'Rounds use 25 seconds per question, with 3/5 hints on 15-question rounds and 5/7 hints on 30-question rounds for easy/hard respectively.',
      'Choose Core or Game, then shuffle across All or drill into a single language.',
      'Each question shows a keyword/syntax term with a code snippet, and 30-question rounds stay non-repeating even in single-language drills.',
    ],
    tryVocab: 'Try Vocab Drill',
    vocabQuestionLabel: 'Term',
    vocabQuestionHint: 'Read the example snippet first, then pick the meaning that best matches the term.',
    vocabGuideTitle: 'Vocab Drill Guide',
    vocabTermLabel: 'Term',
    vocabMeaningLabel: 'Meaning',
    vocabCorrectMeaningLabel: 'Correct meaning',
    vocabResultNote: 'Vocab Drill summary tracks weak spots by language and term.',
    vocabBadge: 'Core + Game · 15/30',
  },
} as const

export type ExtraCopy = (typeof extraCopy)[keyof typeof extraCopy]
